# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x03ksp\"^\n\x0e\x43\x61llLLMRequest\x12\x11\n\tmodel_key\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\"\x1f\n\x0f\x43\x61llLLMResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x10PingModelRequest\x12\x11\n\tmodel_key\x18\x01 \x01(\t\"$\n\x11PingModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"9\n\x13\x45xecuteQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bparams_json\x18\x02 \x01(\t\")\n\x14\x45xecuteQueryResponse\x12\x11\n\trows_json\x18\x01 \x01(\t2~\n\nLLMService\x12\x34\n\x07\x43\x61llLLM\x12\x13.ksp.CallLLMRequest\x1a\x14.ksp.CallLLMResponse\x12:\n\tPingModel\x12\x15.ksp.PingModelRequest\x1a\x16.ksp.PingModelResponse2Q\n\nSQLService\x12\x43\n\x0c\x45xecuteQuery\x12\x18.ksp.ExecuteQueryRequest\x1a\x19.ksp.ExecuteQueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLLLMREQUEST']._serialized_start=23
  _globals['_CALLLLMREQUEST']._serialized_end=117
  _globals['_CALLLLMRESPONSE']._serialized_start=119
  _globals['_CALLLLMRESPONSE']._serialized_end=150
  _globals['_PINGMODELREQUEST']._serialized_start=152
  _globals['_PINGMODELREQUEST']._serialized_end=189
  _globals['_PINGMODELRESPONSE']._serialized_start=191
  _globals['_PINGMODELRESPONSE']._serialized_end=227
  _globals['_EXECUTEQUERYREQUEST']._serialized_start=229
  _globals['_EXECUTEQUERYREQUEST']._serialized_end=286
  _globals['_EXECUTEQUERYRESPONSE']._serialized_start=288
  _globals['_EXECUTEQUERYRESPONSE']._serialized_end=329
  _globals['_LLMSERVICE']._serialized_start=331
  _globals['_LLMSERVICE']._serialized_end=457
  _globals['_SQLSERVICE']._serialized_start=459
  _globals['_SQLSERVICE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
