# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallLLM = channel.unary_unary(
                '/ksp.LLMService/CallLLM',
                request_serializer=services__pb2.CallLLMRequest.SerializeToString,
                response_deserializer=services__pb2.CallLLMResponse.FromString,
                _registered_method=True)
        self.PingModel = channel.unary_unary(
                '/ksp.LLMService/PingModel',
                request_serializer=services__pb2.PingModelRequest.SerializeToString,
                response_deserializer=services__pb2.PingModelResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CallLLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.CallLLM,
                    request_deserializer=services__pb2.CallLLMRequest.FromString,
                    response_serializer=services__pb2.CallLLMResponse.SerializeToString,
            ),
            'PingModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PingModel,
                    request_deserializer=services__pb2.PingModelRequest.FromString,
                    response_serializer=services__pb2.PingModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ksp.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ksp.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ksp.LLMService/CallLLM',
            services__pb2.CallLLMRequest.SerializeToString,
            services__pb2.CallLLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PingModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ksp.LLMService/PingModel',
            services__pb2.PingModelRequest.SerializeToString,
            services__pb2.PingModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SQLServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_unary(
                '/ksp.SQLService/ExecuteQuery',
                request_serializer=services__pb2.ExecuteQueryRequest.SerializeToString,
                response_deserializer=services__pb2.ExecuteQueryResponse.FromString,
                _registered_method=True)


class SQLServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ExecuteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SQLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=services__pb2.ExecuteQueryRequest.FromString,
                    response_serializer=services__pb2.ExecuteQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ksp.SQLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ksp.SQLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SQLService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ksp.SQLService/ExecuteQuery',
            services__pb2.ExecuteQueryRequest.SerializeToString,
            services__pb2.ExecuteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
